FROM python:3.13-slim

# Set env variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app files
COPY . .

# Default command (can be overridden in docker-compose)
CMD ["gunicorn", "-b", "0.0.0.0:5000", "calorie_tracker:app"]
